apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: summit-fhir         ### Change this
  region: us-east-2         ### Change this

nodeGroups:
  - name: summit-fhir-ng-1  ### Change this
    labels:  
      worker: default
    instanceType: m5.xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 4
    ssh:
      allow: false   ### If you want this feature, you'll need a key in ~/.ssh/id_rsa.pub

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: external-dns
      namespace: kube-system
    wellKnownPolicies:
      externalDNS: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true
  - metadata:
      name: build-service
      namespace: ci-cd
    wellKnownPolicies:
      imageBuilder: true

addons:
  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies:
      ebsCSIController: true
